### ISSUE TITLE
issue after training data model

### ISSUE THREAD

**Issue by geek1111** [multunus/autonomous-rc-car#10]
I have trained model with following inputs 
 `python train.py 0.1 60`
`python train.py 0.5 114`
`python train.py 0.5 90`
but car remains idle it doesn't move forward, left, right it just stays idle.....
I'm doing something wrong? 
you can download file [here](https://drive.google.com/file/d/0Bw29Xb_OLHLxTzJBTmdxdVdfMkU/view?usp=sharing)

**Comment by Vignesh1115** [comment]
Hi @geek1111, 
The values of `lambda` and the `hidden layer size` should be chosen with care to prevent the network from overfitting/underfitting the data. The network will underfit for large values of `lambda` and small values of the `hidden layer size`. Similarly, lower values of `lambda` and large values of the `hidden layer size` cause the network to overfit the data and will start incorporating noise into the model. I've not seen examples where the regularisation parameter(`lambda`) is more than 0.1. The rule of the thumb for the number of nodes in the hidden layer is that they are usually between the size of the input layer and the size of the output layer. You could maintain the value of `lambda` below 0.1 and vary the `hidden layer size` while performing cross-validation to determine optimal values for these hyperparameters.

It would be great if we can move conversations around questions you might have to [Gitter](https://gitter.im/autonomous-rc-car/Lobby) instead of this repository. I will be closing this issue.
